name: birds
channels:
  - conda-forge
dependencies:
  - jupyter
  - ipywidgets>=7.4.2
  - bokeh=1.0.4
  - cartopy=0.17.0
  - pyviz/label/dev::datashader=0.7.0a1
  - pyviz/label/dev::geoviews-core=1.6.3a2
  - pyviz/label/dev::holoviews=1.11.3a5
  - pyviz/label/dev::hvplot=0.4.0
  - intake=0.4.1
  - numpy
  - netCDF4
  - pandas>=0.23.4
  - pyviz/label/dev::panel=0.4.1a3
  - xarray
