name: birds
channels:
  - conda-forge
dependencies:
  - jupyter
  - ipywidgets>=7.4.2
  - cartopy==0.17.0
  - intake
  - numpy
  - netCDF4
  - pandas>=0.23.4
  - pyyaml<5.1
  - xarray
  - bokeh/label/dev::bokeh==1.1.0rc1
  - pyviz::colorcet==2.0.1
  - pyviz::geoviews==1.6.2
  - pyviz::holoviews==1.12.0
  - pyviz::hvplot==0.4.0
  - pyviz::panel==0.5.0
