name: birds
channels:
  - conda-forge
dependencies:
  - jupyter
  - ipywidgets>=7.4.2
  - cartopy
  - bokeh/label/dev::bokeh
  - pyviz/label/dev::colorcet
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::hvplot
  - intake
  - numpy
  - pandas>=0.23.4
  - pyyaml<5.1
  - pyviz/label/dev::panel
  - xarray
